### ISSUE TITLE
Latest src is not working (Umd does not match src)

### ISSUE THREAD

**Issue by ipa-jfh** [gkjohnson/urdf-loaders#117]
After running e.g. `npm start` the model does not show up and I get the error:

```js
URDFLoader: Error parsing file. TypeError: "onComplete is not a function"
	load http://localhost:9080/javascript/umd/URDFLoader.js:325:21
```
The current umd does not match the src files. If I open the `index.bundle.html` **before compiling** it works but afterwards the error from above appears. So I think there is some bug in the current src code.

**Comment by gkjohnson** [comment]
Hey! Thanks for the report -- I've been working on updating a few things before releasing a 0.6.0 version and the examples are fully ready, yet.

I'll plan to update the UMD files before publishing to NPM and the reason the error `"onComplete is not a function"` shows up is because the `packages` list has been moved to the options object but the web component hasn't been updated to respect that, yet.

I'll try to address this soon! Thanks again!
