### ISSUE TITLE
Shadow on mesh is broken

### ISSUE THREAD

**Issue by ipa-jfh** [gkjohnson/urdf-loaders#118]
The shadow on the meshes is broken. I do not know the reason but one could e.g. fix it if one reduces `this.directionalLight.shadow.mapSize`. But the "error" might have been introduced in a different way.

Browser: firefox 63.0

### Current:
![image](https://user-images.githubusercontent.com/17281534/52789220-8b641b80-3063-11e9-98cb-50f657696bcc.png)

### E.g. v0.5.0:
![image](https://user-images.githubusercontent.com/17281534/52789154-6079c780-3063-11e9-8e92-a2a59f5ad78e.png)

**Comment by gkjohnson** [comment]
Yeah I noticed that, as well. I think it's because I've removed the shadow bias on the directional light which was causing some disconnected shadows on smaller models but clearly it's causing acne on others. I'll have to look into it a bit more to see what the right solution is. Maybe the bias should be function of the near and far clip planes?
