### ISSUE TITLE
How to reuse toJson and fromJson of  threejs.object3D to make cache available?

### ISSUE THREAD

**Issue by chibai** [gkjohnson/urdf-loaders#253]
All is there any aprroach to save urdfRobot class instance and restore ??

**Comment by gkjohnson** [comment]
Can you describe more specifically what you're trying to do? You can consider the [urdf-exporter](https://github.com/gkjohnson/urdf-exporter-js) project for this need but it might be overkill for your use case. Otherwise if you'd like to contribute toJSON and fromJSON implementations with tests feel free to make a PR and I can provide guidance.
