### ISSUE TITLE
Parse the rest of the URDF (Collision, Intertia)

### ISSUE THREAD

**Issue by gkjohnson** [gkjohnson/urdf-loaders#82]
- [x] Collision Nodes (#122)
- [ ] Inertia Nodes
- [ ] Mimic Nodes

**Comment by chaitanya-deep** [comment]
I wanted to pick this up.
Shall I add `visualEnabled` and `collisionEnabled` in the options similar to RViz?
http://wiki.ros.org/rviz/DisplayTypes/RobotModel#line-9

**Comment by gkjohnson** [comment]
Great! What were you imagining the API looking like? I haven't given it a whole lot of thought.

**Comment by chaitanya-deep** [comment]
I was thinking of something like this
https://github.com/rapyuta-robotics/urdf-loaders/commit/c3974ab0b043d211f06a857fcc9a1e424f40f321

**Comment by gkjohnson** [comment]
I like it being an option to URDFLoader. So you'd load collision geometry like so:
```js
new URDFLoader().load( url, onLoad, null, null, {
    visualEnabled: false,
    collisionEnabled: true,
} );
```

If both `visualEnabled` and `collisionEnabled` are true would it both meshes display on top of each other?

**Comment by chaitanya-deep** [comment]
Yes. I initially thought of an option named `geometryType` which could be `visual` or `collision` but followed RViz. I don't have a preference for either. My current usage doesn't require both the meshes.

Yes if they're both true, they should be displayed on top of each other but since collision should ideally encompass the visual geometry, for most use cases user should never see the visual if both are enabled.
In the case of T12, the visual and collision meshes are the same hence this cannot be seen in action.

**Comment by gkjohnson** [comment]
Closing in favor of #184, #185
